#make test-relu
#make help
#make test-abs
#make test-argmax
#make test-dot
#make test-partA
#make test-matmul
#make test-read_matrix
#make test-partB
#make test-write_matrix
#make test-classify
#make test-main
make test-partB